# Numpy:package for multidimentional array

In [1]:
#numpy=numerical python
import numpy as np

In [2]:
#create array
l=[1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [3]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
l1=[[8,9,10],[4,5,3],[6,7,8]]
np.array(l1)

array([[ 8,  9, 10],
       [ 4,  5,  3],
       [ 6,  7,  8]])

In [5]:
l1=[[8,9,10],[4,5,3],[6,7,8,9]]
np.array(l1)

<ipython-input-5-51196d7cad1d>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array(l1)


array([list([8, 9, 10]), list([4, 5, 3]), list([6, 7, 8, 9])],
      dtype=object)

In [6]:
#wholes numbers
np.arange(0,51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [7]:
#with step 5
np.arange(5,26,5)

array([ 5, 10, 15, 20, 25])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
type(np)

module

In [10]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
#split equally
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [17]:
#identity matrix
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [19]:
#2 rows 4 columns between 0 to 1(uniform distribution)
np.random.rand(2,4)

array([[0.67761253, 0.13882604, 0.32115258, 0.46574796],
       [0.78286973, 0.16476577, 0.59594942, 0.09208195]])

In [20]:
#4 rows 8 columns between 0 to 1
np.random.rand(4,8)

array([[0.36172429, 0.76115734, 0.91210348, 0.74675828, 0.65581282,
        0.72384216, 0.19043579, 0.84896241],
       [0.66502853, 0.48440038, 0.02024966, 0.70085276, 0.76399858,
        0.95769268, 0.51773052, 0.50116376],
       [0.94623734, 0.09641679, 0.87206309, 0.73074105, 0.18268187,
        0.79473526, 0.22874624, 0.59751404],
       [0.00157319, 0.46127548, 0.16201898, 0.30784586, 0.25267542,
        0.26604712, 0.95266916, 0.153394  ]])

In [21]:
#2 rows 4 columns postive and negatives(normal distribution)
np.random.randn(2,4)

array([[ 0.65591037,  0.25850621,  0.93166009,  0.75835864],
       [-2.11039862, -0.01369303, -0.58202657,  1.21395079]])

In [22]:
np.random.randint(2,10)

3

In [23]:
s=np.random.randint(25,60,50)
s

array([44, 38, 48, 51, 25, 49, 35, 28, 38, 40, 46, 37, 49, 28, 41, 35, 51,
       27, 47, 45, 37, 34, 33, 31, 54, 45, 40, 34, 26, 42, 58, 25, 28, 47,
       58, 39, 47, 43, 45, 30, 31, 36, 25, 30, 49, 34, 45, 35, 44, 39])

In [24]:
a=np.arange(30)

In [25]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
a.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [27]:
#multiplied values should give 30
a.reshape(5,9)

ValueError: cannot reshape array of size 30 into shape (5,9)

In [ ]:
s.min()

In [ ]:
s.max()

In [28]:
s.argmin()

4

In [29]:
#gives index
s.argmax()

30

In [30]:
#index
s.argmin()

4

In [31]:
r=np.random.randint(20,80,40)

In [32]:
r

array([53, 29, 38, 43, 74, 52, 73, 39, 61, 23, 36, 28, 21, 54, 61, 61, 33,
       53, 65, 71, 55, 50, 79, 47, 47, 21, 21, 62, 48, 62, 67, 47, 55, 60,
       74, 78, 36, 62, 31, 46])

In [33]:
r.max()


79

In [34]:
r.argmax()

22

In [35]:
m=np.eye(5)

In [36]:
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
#Transpose
m.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
d=np.random.rand(3,10)
d

array([[0.65511356, 0.41247685, 0.25820411, 0.11084802, 0.91873065,
        0.30142947, 0.01713399, 0.64780085, 0.67455503, 0.60295894],
       [0.95018313, 0.96872937, 0.05620377, 0.28996898, 0.48914202,
        0.00810094, 0.63629775, 0.16606843, 0.46355257, 0.07370178],
       [0.85088647, 0.97609487, 0.29448348, 0.52516521, 0.86328495,
        0.34970889, 0.5359475 , 0.92510962, 0.72824412, 0.59760944]])

In [39]:
d.T

array([[0.65511356, 0.95018313, 0.85088647],
       [0.41247685, 0.96872937, 0.97609487],
       [0.25820411, 0.05620377, 0.29448348],
       [0.11084802, 0.28996898, 0.52516521],
       [0.91873065, 0.48914202, 0.86328495],
       [0.30142947, 0.00810094, 0.34970889],
       [0.01713399, 0.63629775, 0.5359475 ],
       [0.64780085, 0.16606843, 0.92510962],
       [0.67455503, 0.46355257, 0.72824412],
       [0.60295894, 0.07370178, 0.59760944]])

In [40]:
slice=np.random.randint(2,10,12)

In [41]:
#works based on index
slice

array([3, 9, 4, 9, 5, 9, 8, 2, 5, 2, 9, 5])

In [42]:
slice[2:5]

array([4, 9, 5])

In [43]:
slice[1:4]=50

In [44]:
slice

array([ 3, 50, 50, 50,  5,  9,  8,  2,  5,  2,  9,  5])

In [45]:
s2=np.arange(20,34)

In [46]:
s2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [47]:
s2[0:7]

array([20, 21, 22, 23, 24, 25, 26])

In [48]:
s2[:]=40

In [49]:
s2

array([40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40])

### 2D array

In [50]:
s3=np.array(([40,35,23],[23,45,64],[34,67,89],[32,45,32]))
s3

array([[40, 35, 23],
       [23, 45, 64],
       [34, 67, 89],
       [32, 45, 32]])

In [51]:
s3[1,2]

64

In [52]:
s3[1:2]

array([[23, 45, 64]])

In [53]:
s3[2,:]

array([34, 67, 89])

In [54]:
s3[2]

array([34, 67, 89])

In [55]:
s3[:,(2,1)]

array([[23, 35],
       [64, 45],
       [89, 67],
       [32, 45]])

##### selection techniques

In [56]:
array=np.arange(20,80)

In [57]:
array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79])

In [58]:
array+array

array([ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,  62,  64,
        66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,  88,  90,
        92,  94,  96,  98, 100, 102, 104, 106, 108, 110, 112, 114, 116,
       118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142,
       144, 146, 148, 150, 152, 154, 156, 158])

In [59]:
np.exp(array)

array([4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16,
       2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
       1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
       7.01673591e+20, 1.90734657e+21, 5.18470553e+21, 1.40934908e+22,
       3.83100800e+22, 1.04137594e+23, 2.83075330e+23, 7.69478527e+23,
       2.09165950e+24, 5.68572000e+24, 1.54553894e+25, 4.20121040e+25,
       1.14200739e+26, 3.10429794e+26, 8.43835667e+26, 2.29378316e+27,
       6.23514908e+27, 1.69488924e+28, 4.60718663e+28, 1.25236317e+29,
       3.40427605e+29, 9.25378173e+29, 2.51543867e+30, 6.83767123e+30,
       1.85867175e+31, 5.05239363e+31, 1.37338298e+32, 3.73324200e+32,
      

In [60]:
np.sqrt(array)

array([4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
       8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386,
       8.36660027, 8.42614977, 8.48528137, 8.54400375, 8.60232527,
       8.66025404, 8.71779789, 8.77496439, 8.83176087, 8.88819442])

In [61]:
np.log(array)

array([2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165,
       3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
       3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ,
       3.91202301, 3.93182563, 3.95124372, 3.97029191, 3.98898405,
       4.00733319, 4.02535169, 4.04305127, 4.06044301, 4.07753744,
       4.09434456, 4.11087386, 4.12713439, 4.14313473, 4.15888308,
       4.17438727, 4.18965474, 4.20469262, 4.21950771, 4.2341065 ,
       4.24849524, 4.26267988, 4.27666612, 4.29045944, 4.30406509,
       4.31748811, 4.33073334, 4.34380542, 4.35670883, 4.36944785])

In [62]:
np.max(array)

79

In [63]:
np.min(array)

20

In [64]:
np.argmax(array)

59

In [65]:
np.argmin(array)

0

In [66]:
np.square(array)

array([ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841,  900,
        961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681,
       1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704,
       2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969,
       4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476,
       5625, 5776, 5929, 6084, 6241], dtype=int32)

In [67]:
np.std(array)

17.318102282486574

In [68]:
np.var(array)

299.9166666666667

In [69]:
np.mean(array)

49.5

In [70]:
arr2=np.random.randn(2,7)

In [71]:
arr2

array([[ 1.54546926, -1.88214615,  0.08529839, -0.94453884, -0.80947362,
        -2.22097982, -0.45874748],
       [-1.66981764, -1.31431522,  0.774268  , -0.46747089,  1.27742398,
        -1.15406557, -0.71420424]])

In [72]:
np.round(arr2,decimals=2)

array([[ 1.55, -1.88,  0.09, -0.94, -0.81, -2.22, -0.46],
       [-1.67, -1.31,  0.77, -0.47,  1.28, -1.15, -0.71]])

In [73]:
names=np.array(['karan','charan','riya','hari'])

In [74]:
names

array(['karan', 'charan', 'riya', 'hari'], dtype='<U6')

In [75]:
np.unique(names)

array(['charan', 'hari', 'karan', 'riya'], dtype='<U6')